export const TRY_SET_USER = 'TRY_SET_USER';
export const SET_USER = 'SET_USER';
export const TRY_SENT_CHAT_MSG = 'TRY_SENT_CHAT_MSG';

export const SENT_CHAT_MSG2 = 'SENT_CHAT_MSG2';
export const SENT_CHAT_MSG = 'SENT_CHAT_MSG';

export const INITIALIZE_WEB_SOCKETS_CHANNEL = 'INITIALIZE_WEB_SOCKETS_CHANNEL';
